### ISSUE TITLE
policyの階層構造

### ISSUE THREAD

**Issue by masibw** [Tomo-9925/cnet#33]
```
policies:
  - container:
      name: "nginx_test"
    communications:
      - processes:
          - path: "/usr/sbin/nginx"
        sockets:
          - protocol: "tcp"
            local_port: 80
          - protocol: "tcp"
            local_port: 443
```

containerの属性として「name」「communications」があると思ってるんですがnameがcommunicationsより1階層低いの違和感ありません？
